name: Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CRI_BIN: podman
      CHECKUP_IMAGE_TAG: ${{github.ref_name}}
      TRAFFIC_GEN_IMAGE_TAG: ${{github.ref_name}}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Login to quay.io
        run:
          ${CRI_BIN} login -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_TOKEN }} quay.io
      - name: Build checkup image
        run: make build
      - name: Push checkup image
        run: make push
